TrajectoryPlannerROS:
  max_vel_x: 0.20
  min_vel_x: 0.10
  max_rotational_vel: 0.7
  min_in_place_rotational_vel: 0.1

  acc_lim_th: 3.0
  acc_lim_x: 0.7

  holonomic_robot: false
  
  sim_time: 4.0
  sim_granularity: 0.05
  
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true
  
  vx_samples: 8
  controller_frequency: 5

  